### ISSUE TITLE
Приходит два письма: об изменении статуса оплаты и об оплате в Яндекс.Касса

### ISSUE THREAD

**Issue by r3code** [yandex-money/yandex-money-cms-hostcms#5]
Администраторов магазина раздражает, что приходит два практически одинаковых письма о факте оплаты при оплате через Кассу.
Одно письмо об изменении статуса оплаты, второе подтверждение оплаты от Яндекс.Касса.

**Comment by actofgod** [comment]
В последней версии добавлено свойство sendChangeStatusEmail, установите его в false для отключения отправки администраторам имейлов при создании заказов, но до их оплаты.

**Comment by r3code** [comment]
@actofgod Отлично!
