### ISSUE TITLE
Темы писем, заданные в настройках интернет-магазина, игнорируются

### ISSUE THREAD

**Issue by maximzasorin** [yandex-money/yandex-money-cms-hostcms#9]
В версии HostCMS 6.7.1 была добавлена возможность настраивать темы для писем, которые отправляются в случае оплаты или отмены оплаты заказа. Для поддержки этого нововведения был добавлен метод `setMailSubjects`, в обработчике оплаты данный метод не используется, а темы писем, настроенные пользователями, игнорируются.

**Comment by actofgod** [comment]
Добавлено в новой версии (см. pull request #12 )

**Comment by maximzasorin** [comment]
Спасибо.

2017-08-22 15:51 GMT+03:00 Alexander <notifications@github.com>:
